# Generated by Django 3.0.3 on 2021-04-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('competition_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('competition_turn', models.CharField(max_length=20)),
                ('cubeevent', models.CharField(db_column='CubeEvent', max_length=20)),
                ('competition_time', models.DateTimeField(blank=True, null=True)),
                ('scramble1', models.CharField(blank=True, max_length=100, null=True)),
                ('scramble2', models.CharField(blank=True, max_length=100, null=True)),
                ('scramble3', models.CharField(blank=True, max_length=100, null=True)),
                ('scramble4', models.CharField(blank=True, max_length=100, null=True)),
                ('scramble5', models.CharField(blank=True, max_length=100, null=True)),
                ('scramble_extra1', models.CharField(blank=True, max_length=100, null=True)),
                ('scramble_extra2', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'competition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompetitionTime',
            fields=[
                ('competition_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('competition_turn', models.CharField(max_length=20)),
                ('cubeevent', models.CharField(db_column='CubeEvent', max_length=20)),
                ('studentnumber', models.CharField(max_length=20)),
                ('time1', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('time2', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('time3', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('time4', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('time5', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'db_table': 'competition_time',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatabaseLogin',
            fields=[
                ('student_no', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'database_login',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('passwd', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'login',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('studentnumber', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('college', models.CharField(blank=True, max_length=20, null=True)),
                ('major', models.CharField(blank=True, max_length=30, null=True)),
                ('passwd', models.CharField(max_length=20)),
                ('wcaid', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'person',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('cubeevent', models.CharField(db_column='CubeEvent', max_length=20, primary_key=True, serialize=False)),
                ('name_single', models.CharField(blank=True, max_length=20, null=True)),
                ('time_single', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('name_average', models.CharField(blank=True, max_length=20, null=True)),
                ('time_average', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'db_table': 'record',
                'managed': False,
            },
        ),
    ]
